version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-rss-datasource
      - ./provisioning:/etc/grafana/provisioning
  server:
    container_name: xml-server
    build:
      context: ./xml-server
    ports:
      - 8001:8001
