version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-rss-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  server:
    container_name: xml-server
    build:
      context: ./xml-server
    ports:
      - 8001:8001
    profiles:
      - dev
      - main

  grafana-main:
    container_name: grafana-main
    image: grafana/grafana:main
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-rss-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  test:
    container_name: test-e2e
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://127.0.0.1:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    network_mode: host
    profiles:
      - e2e
